PUT http://localhost:8081/api/search
Content-Type: application/json

{
  "searchWords":["hello "]
}

###
POST http://localhost:8081/api/search
Content-Type: application/json

{
    "searchWords":["hello "]
}

###

POST http://localhost:8081/api/search
Content-Type: application/json

{
   "searchWords": ["sample"]
}

###
