server:
  port: 8081

cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-east-2
    credentials:
      access-key: AKIAU4ZXNRXBOVHXSU5T
      secret-key: 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
    end-point:
      uri: https://sqs.us-east-2.amazonaws.com/336734293442/search.fifo


spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: search
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer